apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: admin-role-2
 namespace: dev
roleRef:
 kind: ClusterRole
 name: view
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: ken
   namespace: dev

