apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: read-only-pods
 namespace: prometheus
roleRef:
 kind: Role
 name: role-carol 
 apiGroup: rbac.authorization.k8s.io
subjects: 
 - kind: ServiceAccount
   name: carol
   namespace: prometheus
