apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: bob
subjects:
  - kind: ServiceAccount
    name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
