apiVersion: v1
kind: Service
metadata:
 name: coredns-svc-tcp
 annotations:
   metallb.universe.tf/allow-shared-ip: "172.17.255.3"
spec:
 selector: 
  k8s-app: kube-dns
 type: LoadBalancer
 loadBalancerIP: 172.17.255.3
 ports:
  - name: tcp 
    protocol: TCP
    port: 53 
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
 name: coredns-svc-lb-udp
 annotations:
   metallb.universe.tf/allow-shared-ip: "172.17.255.3"
spec:
 selector:
  k8s-app: kube-dns
 type: LoadBalancer
 loadBalancerIP: 172.17.255.3
 ports:
  - name: udp
    protocol: UDP
    port: 53
    targetPort: 53

